# 도커 컴포즈 파일 형식 버전을 정의합니다.
version: '3.8'

# 여기에 우리가 관리할 서비스(컨테이너)들을 정의합니다.
services:
  # 첫 번째 서비스: 로드 밸런서
  load-balancer:
    # 'load_balancer' 폴더에 있는 Dockerfile을 사용하여 이미지를 빌드합니다.
    build: ./load_balancer
    # 이 서비스에 'lb-service' 라는 고정된 이름을 부여합니다.
    container_name: lb-service
    # 내 컴퓨터의 7100번 포트와 컨테이너의 7100번 포트를 연결합니다.
    ports:
      - "7100:7100"
    # 이 서비스가 사용할 네트워크를 지정합니다.
    networks:
      - titanium-net  # [수정] api-gateway와 동일한 네트워크로 변경
    # 웹 대시보드 파일을 컨테이너 안으로 연결(마운트)합니다.
    volumes:
      - ./data:/app/data

  # 두 번째 서비스: API 게이트웨이
  api-gateway:
    build: ./api_gateway
    container_name: api-gateway-service
    # API 게이트웨이의 포트는 외부로 노출하지 않습니다.
    networks:
      - titanium-net
    # 데이터베이스 파일이 컨테이너가 삭제되어도 유지되도록 내 컴퓨터와 연결합니다.
    volumes:
      - ./api_gateway/data:/app/data
    # 로드 밸런서가 먼저 준비된 후에 시작되도록 의존성을 설정합니다.
    depends_on:
      - load-balancer

# 서비스들이 사용할 공용 네트워크를 정의합니다.
networks:
  titanium-net:
    # 이 네트워크는 'bridge' 방식으로 동작합니다.
    driver: bridge
