services:
  load-balancer:
    image: dongju101/titanium-lb:latest
    container_name: lb-service
    ports:
      - "7100:7100"
    networks:
      - titanium-net
    volumes:
      - ./dashboard-ui:/app/static # UI 파일을 위한 볼륨 경로 수정
    depends_on:
      - api-gateway
    # [추가됨] 환경 변수를 컨테이너에 주입합니다.
    environment:
      - INTERNAL_API_SECRET=${INTERNAL_API_SECRET}

  api-gateway:
    image: dongju101/titanium-api:latest
    container_name: api-gateway-service
    networks:
      - titanium-net
    volumes:
      - api_gateway_data:/app/data
    # [추가됨] 동일한 비밀 키를 api-gateway에도 주입합니다.
    environment:
      - INTERNAL_API_SECRET=${INTERNAL_API_SECRET}

  dashboard-ui:
    image: dongju101/titanium-ui:latest
    container_name: dashboard-ui-service
    networks:
      - titanium-net

networks:
  titanium-net:
    driver: bridge

volumes:
  api_gateway_data:
