apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service-container
        # skaffold.yaml에 정의된 이미지 이름과 일치해야 합니다.
        image: dongju101/titanium-analytics-service
        ports:
        - containerPort: 8004
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10