apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    component: auth
    app.kubernetes.io/name: titanium
    app.kubernetes.io/component: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: http
    name: http
  sessionAffinity: None