apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    component: cache
    app.kubernetes.io/name: titanium
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: redis
    name: redis
  sessionAffinity: None