apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    component: backend
    app.kubernetes.io/name: titanium
    app.kubernetes.io/component: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: http
    name: http
  sessionAffinity: None