# 로컬 개발용 리소스 제한 완화 및 개발 최적화
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  template:
    metadata:
      annotations:
        titanium.io/environment: local
        titanium.io/debug-mode: "true"
    spec:
      containers:
      - name: api-gateway-container
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "500Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: DEV_MODE
          value: "true"
        - name: AUTO_RELOAD
          value: "true"
        # Health Check 간격 완화 (개발 편의성)
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 60  # 개발 중 긴 시작시간 허용
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
spec:
  template:
    metadata:
      annotations:
        titanium.io/environment: local
        titanium.io/debug-mode: "true"
    spec:
      containers:
      - name: load-balancer-container
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "500Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: DEV_MODE
          value: "true"
        - name: VERBOSE_LOGGING
          value: "true"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  template:
    metadata:
      annotations:
        titanium.io/environment: local
    spec:
      containers:
      - name: auth-service-container
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "500Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: SKIP_AUTH_VALIDATION
          value: "true"  # 개발 편의성
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  template:
    metadata:
      annotations:
        titanium.io/environment: local
    spec:
      containers:
      - name: user-service-container
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "500Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: MOCK_DATA_ENABLED
          value: "true"  # 개발용 모킹 데이터
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-ui-deployment
spec:
  template:
    metadata:
      annotations:
        titanium.io/environment: local
    spec:
      containers:
      - name: dashboard-ui-container
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
            ephemeral-storage: "200Mi"
          limits:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "500Mi"
        env:
        - name: NODE_ENV
          value: "development"
        - name: API_BASE_URL
          value: "http://localhost:30700"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  template:
    metadata:
      annotations:
        titanium.io/environment: local
        titanium.io/persistence: "false"
    spec:
      containers:
      - name: redis-container
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
            ephemeral-storage: "200Mi"
          limits:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "500Mi"
        # 로컬에서는 영속성 비활성화 (빠른 재시작)
        livenessProbe:
          initialDelaySeconds: 10
        readinessProbe:
          initialDelaySeconds: 5
---
# 로컬 개발용 PVC 크기 축소
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-data-pvc
spec:
  resources:
    requests:
      storage: 100Mi  # 로컬 개발용으로 축소