apiVersion: v1
kind: Service
metadata:
  # 이 서비스의 고유한 이름입니다.
  name: api-gateway-service
spec:
  # 서비스 타입을 ClusterIP로 지정합니다. (클러스터 내부 통신용)
  type: ClusterIP
  # [핵심!] 이 서비스가 어떤 파드들을 묶어줄지 선택하는 규칙입니다.
  # 'app: api-gateway' 라벨이 붙은 파드들을 찾아냅니다.
  selector:
    app: api-gateway
  # 포트 설정
  ports:
    - protocol: TCP
      # 이 서비스 자체는 8000번 포트로 요청을 받습니다.
      port: 8000
      # 받은 요청을 파드의 8000번 포트로 전달합니다.
      targetPort: 8000