# k8s-manifests/auth-service-service.yml
apiVersion: v1
kind: Service
metadata:
  # 다른 서비스들이 이 이름(auth-service)을 사용하여 접속하게 됩니다.
  name: auth-service
spec:
  # ClusterIP는 클러스터 내부에서만 접근 가능한 고정 IP를 할당합니다.
  type: ClusterIP
  # 'app: auth-service' 이름표가 붙은 파드들을 이 서비스에 연결합니다.
  selector:
    app: auth-service
  ports:
  - port: 8002
    targetPort: 8002
