# k8s-manifests/auth-service-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  # 이 서비스를 몇 개의 파드로 실행할지 결정합니다.
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      # 파드에 'app: auth-service' 라는 이름표를 붙입니다.
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service-container
        # CI/CD 파이프라인에서 빌드할 Docker 이미지 이름입니다.
        image: dongju101/titanium-auth-service:latest
        ports:
        - containerPort: 8002 # auth-service는 8002번 포트를 사용합니다.
        envFrom:
          # 'app-config' ConfigMap의 모든 데이터를 환경 변수로 주입합니다.
          # (USER_SERVICE_URL 등을 가져오기 위함)
          - configMapRef:
              name: app-config
