# k8s-manifests/k8s-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  # 모든 서비스가 공통으로 참조할 ConfigMap의 이름입니다.
  name: app-config
data:
  # --- Load Balancer가 사용하는 환경 변수 ---
  # API_GATEWAY_URL과 DASHBOARD_UI_URL은 load_balancer/config.py에서 사용됩니다.
  API_GATEWAY_URL: "http://api-gateway-service:8000"
  DASHBOARD_UI_URL: "http://dashboard-ui-service:80"

  # --- API Gateway가 사용하는 환경 변수 ---
  # api_gateway/config.py에서 이 주소들을 사용하여 다른 서비스를 호출합니다.
  LOAD_BALANCER_URL: "http://load-balancer-service:7100"
  USER_SERVICE_URL: "http://user-service:8001"
  AUTH_SERVICE_URL: "http://auth-service:8002"

  # --- User Service가 사용하는 환경 변수 ---
  # user-service/config.py에서 Redis에 접속하기 위해 이 값을 사용합니다.
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # --- Auth Service가 사용하는 환경 변수 ---
  # auth-service/config.py에서 User Service를 호출하기 위해 이 값을 사용합니다.
  # USER_SERVICE_URL은 이미 위에서 정의되었으므로, Auth Service도 동일한 값을 참조합니다.
