# k8s-manifests/k8s-secret.yml
apiVersion: v1
kind: Secret
metadata:
  # Secret의 이름을 지정합니다.
  name: app-secrets
type: Opaque # 일반적인 형태의 Secret을 의미합니다.
data:
  # [중요!] Secret에 저장되는 모든 값은 반드시 Base64로 인코딩되어야 합니다.
  # 터미널에서 'echo -n "원하는비밀키" | base64' 명령으로 인코딩된 값을 생성할 수 있습니다.
  # 예: echo -n "this-is-a-very-secret-key" | base64 -> dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleQ==
  INTERNAL_API_SECRET: dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleQ==
