apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  # [핵심!] 서비스 타입을 NodePort로 지정하여 외부 접속을 허용합니다.
  type: NodePort
  selector:
    app: load-balancer
  ports:
    - protocol: TCP
      # 클러스터 내부에서 이 서비스는 7100 포트로 접근됩니다.
      port: 7100
      # 파드의 7100 포트로 트래픽을 전달합니다.
      targetPort: 7100
      # [핵심!] 클러스터 외부에서는 30700번 포트로 이 서비스에 접근할 수 있습니다.
      # NodePort의 범위는 보통 30000-32767 입니다.
      nodePort: 30700