apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
spec:
  replicas: 1 # 로드밸런서는 보통 하나만 둡니다.
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
      - name: load-balancer-container
        # 방금 새로 빌드한 이미지를 사용합니다.
        image: dongju101/titanium-lb:latest
        ports:
        - containerPort: 7100