# k8s-manifests/user-service-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-container
        image: dongju101/titanium-user-service:latest # CI/CD에서 빌드할 새 이미지
        ports:
        - containerPort: 8001
        envFrom: # Redis 접속 정보 등을 ConfigMap에서 가져옴
        - configMapRef:
            name: app-config
        volumeMounts: # 데이터베이스 파일을 저장할 영구 볼륨 마운트
        - name: user-data
          mountPath: /data
      volumes:
      - name: user-data
        persistentVolumeClaim:
          claimName: user-service-data-pvc # 아래에서 정의할 PVC
