# k8s-manifests/user-service-pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

