# API Gateway의 복제본 수를 1로 설정
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1

---
# User Service의 복제본 수를 1로 설정
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1